print('Olá, a fórmula desse arquivo é A + B * B - A')
A = int(input("Primeiro número: "))
B = int(input("Segundo número: "))
S = (A + (B * B) - A)
print("Com o valor de A {} e o de B sendo {} o resultado é {}".format(A, B, S))
